AWSTemplateFormatVersion: '2010-09-09'

Description: Cloudformation resource template.

Resources:
  DocRetrieverRepo: # repo holding the serverless container image for grant docs retriever
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "uspto-grants-doc-repository"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]]
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"

  # AppDocRepo: # repo holding the serverless container image for application docs retriever
  #   Type: AWS::ECR::Repository
  #   Properties: 
  #     RepositoryName: "uspto-app-doc-repository"
  #     RepositoryPolicyText: 
  #       Version: "2012-10-17"
  #       Statement: 
  #         - 
  #           Sid: AllowPushPull
  #           Effect: Allow
  #           Principal: 
  #             AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]]
  #           Action: 
  #             - "ecr:GetDownloadUrlForLayer"
  #             - "ecr:BatchGetImage"
  #             - "ecr:BatchCheckLayerAvailability"
  #             - "ecr:PutImage"
  #             - "ecr:InitiateLayerUpload"
  #             - "ecr:UploadLayerPart"
  #             - "ecr:CompleteLayerUpload"
  #             - "ecr:GetAuthorizationToken"            
  
  DocRetrieverStackS3Bucket: # bucket holding the serverless template file
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: doc-retriever-stack-bucket
      AccessControl: BucketOwnerFullControl

  DocStorageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: uspto-documents-storage
      AccessControl: BucketOwnerFullControl
  
  DocStorageBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: uspto-documents-storage
      PolicyDocument:
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - arn:aws:s3:::uspto-documents-storage/* 
          - Sid: ReadWrite
            Effect: Allow
            Principal: 
              AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]] 
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::uspto-documents-storage/*

  MountTargetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/20
      Tags:
       - Key: stack
         Value: psv      
 
  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: MountTargetVPC
      GroupDescription: "mnt target sg"
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: "0.0.0.0/0"

  MountTargetSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "us-east-1a"
      Tags:
       - Key: stack
         Value: psv
 
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: stack
          Value: psv

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref MountTargetSubnetOne
      SecurityGroups:
      - !Ref EfsSecurityGroup
 
  AccessPointResource:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref FileSystemResource
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: "/psv_efs"

Outputs:
  AccessPointResourceArn:
    Description: "The EFS access point resource"
    Value: !GetAtt AccessPointResource.Arn
    Export:
      Name: 'AccessPointResourceArn'
    
