AWSTemplateFormatVersion: '2010-09-09'

Description: Cloudformation resource template.

Resources:
  DocRetrieverRepo: # repo holding the serverless container image for grant docs retriever
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "uspto-grants-doc-repository"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]]
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"

  # AppDocRepo: # repo holding the serverless container image for application docs retriever
  #   Type: AWS::ECR::Repository
  #   Properties: 
  #     RepositoryName: "uspto-app-doc-repository"
  #     RepositoryPolicyText: 
  #       Version: "2012-10-17"
  #       Statement: 
  #         - 
  #           Sid: AllowPushPull
  #           Effect: Allow
  #           Principal: 
  #             AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]]
  #           Action: 
  #             - "ecr:GetDownloadUrlForLayer"
  #             - "ecr:BatchGetImage"
  #             - "ecr:BatchCheckLayerAvailability"
  #             - "ecr:PutImage"
  #             - "ecr:InitiateLayerUpload"
  #             - "ecr:UploadLayerPart"
  #             - "ecr:CompleteLayerUpload"
  #             - "ecr:GetAuthorizationToken"            
  
  DocRetrieverStackS3Bucket: # bucket holding the serverless template file
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: doc-retriever-stack-bucket
      AccessControl: BucketOwnerFullControl

  DocStorageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: uspto-documents-storage
      AccessControl: BucketOwnerFullControl
  
  DocStorageBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: uspto-documents-storage
      PolicyDocument:
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - arn:aws:s3:::uspto-documents-storage/* 
          - Sid: ReadWrite
            Effect: Allow
            Principal: 
              AWS: !Join [':', ['arn:aws:iam:', !Ref AWS::AccountId, user/psv_app]] 
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::uspto-documents-storage/*     