AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  USPTO grant and application bulk document retriever SAM stack

Globals:
  Function:
    Timeout: 900

Parameters:
  AwsAccessKeyId:
    Type: String
    Description: AWS access key Id.
  AwsSecretAccessKey:
    Type: String
    Description: AWS key secret.
  AwsRegion:
    Type: String
    Description: The AWS Region.
  NodeEnv:
    Type: String
    Description: The nodejs Environment.
  EFSpath:
    Type: String
    Default: "/mnt/efs0"

Resources:
  GrantDocRetrieverFunction:
    Type: AWS::Serverless::Function
    Handler: ./grant-doc-retriever/app.lambdaHandler
    Timeout: 900
    Properties:
      CodeUri: ./
      Description: Process the bulk USPTO grants files
      PackageType: Image
      MemorySize: 10240
      Tracing: Active
      ImageUri:
        !Join [
          ".",
          [
            !Ref AWS::AccountId,
            "dkr.ecr",
            !Ref AWS::Region,
            "amazonaws.com/",
            !Ref DocRetrieverRepo,
          ],
        ]
      Environment:
        Variables:
          PSV_AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
          PSV_AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
          PSV_AWS_REGION: !Ref AwsRegion
          EFS_PATH: !Ref EFSpath
          NODE_ENV: !Ref NodeEnv
      Events:
        DocRetrieverEvent:
          Type: Api
          Properties:
            Path: grant/retrieve
            Method: post
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(59 23 ? * 3 *)
      FileSystemConfigs:
        - LocalMountPath: !Ref EFSpath
          Arn:
            Fn::ImportValue: EfsAccessPointArn
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: "PsvPrivateSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: "PsvPrivateSubnetOne"
          - Fn::ImportValue: "PsvPrivateSubnetTwo"
      Policies:
        - AWSXRayDaemonWriteAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonElasticFileSystemClientReadWriteAccess
        - AmazonS3FullAccess

    Metadata:
      DockerTag: grant-doc-retriever
      DockerContext: ./
      Dockerfile: ./grant-doc-retriever/Dockerfile

  AppDocRetrieverFunction:
    Type: AWS::Serverless::Function
    Handler: app.lambdaHandler
    CodeUri: ./application-doc-retriever
    Properties:
      MemorySize: 10240
      PackageType: Image
      ImageUri:
        !Join [
          ".",
          [
            !Ref AWS::AccountId,
            "dkr.ecr",
            !Ref AWS::Region,
            "amazonaws.com/",
            !Ref DocRetrieverRepo,
          ],
        ]
      Environment:
        Variables:
          PSV_AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
          PSV_AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
          PSV_AWS_REGION: !Ref AwsRegion
          NODE_ENV: !Ref NodeEnv
      Events:
        DocRetrieverEvent:
          Type: Api
          Properties:
            Path: app/retrieve
            Method: post
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(59 23 ? * 5 *)
    Metadata:
      DockerTag: app-doc-retriever
      DockerContext: ./
      Dockerfile: ./application-doc-retriever/Dockerfile

Outputs:
  GrantDocRetrieverApi:
    Description: "API Gateway endpoint URL for Prod stage for GrantDocRetrieverApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/grant/retrieve/"
  GrantDocRetrieverFunction:
    Description: "DocRetriever Lambda Function ARN"
    Value: !GetAtt GrantDocRetrieverFunction.Arn
  GrantDocRetrieverFunctionIamRole:
    Description: "Implicit IAM Role created for DocRetriever function"
    Value: !GetAtt GrantDocRetrieverFunctionRole.Arn
  ApplicationDocRetrieverApi:
    Description: "API Gateway endpoint URL for Prod stage for ApplicationDocRetrieverApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app/retrieve/"
  AppDocRetrieverFunction:
    Description: "DocRetriever Lambda Function ARN"
    Value: !GetAtt AppDocRetrieverFunction.Arn
  AppDocRetrieverFunctionIamRole:
    Description: "Implicit IAM Role created for DocRetriever function"
    Value: !GetAtt AppDocRetrieverFunctionRole.Arn
