AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  USPTO grant and application bulk document retriever SAM stack

Globals:
  Function:
    Timeout: 900

Parameters:
  AwsAccessKeyId:
    Type: String
    Description: AWS access key Id.
  AwsSecretAccessKey:
    Type: String
    Description: AWS key secret.
  AwsRegion:
    Type: String
    Description: The AWS Region.
  NodeEnv:
    Type: String
    Description: The nodejs Environment.
    
Resources:
  GrantDocRetrieverFunction:
    Type: AWS::Serverless::Function
    Handler: ./grant-doc-retriever/app.lambdaHandler
    CodeUri: ./
    Properties:
      PackageType: Image
      ImageUri: !Join ['.', [!Ref AWS::AccountId, 'dkr.ecr', !Ref AWS::Region, 'amazonaws.com/', !Ref DocRetrieverRepo]]
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
          AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
          AWS_REGION: !Ref AwsRegion
          NODE_ENV: !Ref NodeEnv

      Events:
        DocRetrieverEvent:
          Type: Api
          Properties:
            Path: grant/retrieve
            Method: post
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(59 23 * * 2)

    Metadata:
      DockerTag: grant-doc-retriever
      DockerContext: ./ 
      Dockerfile: ./grant-doc-retriever/Dockerfile
  
  AppDocRetrieverFunction:
    Type: AWS::Serverless::Function
    Handler: app.lambdaHandler
    CodeUri: ./application-doc-retriever
    Properties:
      PackageType: Image
      ImageUri: !Join ['.', [!Ref AWS::AccountId, 'dkr.ecr', !Ref AWS::Region, 'amazonaws.com/', !Ref DocRetrieverRepo]]
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
          AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
          AWS_REGION: !Ref AwsRegion
          NODE_ENV: !Ref NodeEnv
      Events:
        DocRetrieverEvent:
          Type: Api
          Properties:
            Path: app/retrieve
            Method: post
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(59 23 * * 4)

    Metadata:
      DockerTag: app-doc-retriever
      DockerContext: ./
      Dockerfile: ./application-doc-retriever/Dockerfile

Outputs:
  GrantDocRetrieverApi:
    Description: "API Gateway endpoint URL for Prod stage for GrantDocRetrieverApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/grant/retrieve/"
  GrantDocRetrieverFunction:
    Description: "DocRetriever Lambda Function ARN"
    Value: !GetAtt GrantDocRetrieverFunction.Arn
  GrantDocRetrieverFunctionIamRole:
    Description: "Implicit IAM Role created for DocRetriever function"
    Value: !GetAtt GrantDocRetrieverFunctionRole.Arn
  ApplicationDocRetrieverApi:
    Description: "API Gateway endpoint URL for Prod stage for ApplicationDocRetrieverApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app/retrieve/"
  AppDocRetrieverFunction:
    Description: "DocRetriever Lambda Function ARN"
    Value: !GetAtt AppDocRetrieverFunction.Arn
  AppDocRetrieverFunctionIamRole:
    Description: "Implicit IAM Role created for DocRetriever function"
    Value: !GetAtt AppDocRetrieverFunctionRole.Arn    
